services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    ports:
      - '8080:8080'
    volumes:
      - '.:/src'
    command:
      [
        "uvicorn",
        'src.main:app',
        '--host',
        "0.0.0.0",
        '--port',
        '8080',
      ]
