services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SQL_DB=users
      - SMTP_HOST=''
      - SMTP_USER=''
      - SMTP_PASSWORD=''
      - EMAILS_FROM_EMAIL=email@example.com
      - FIRST_SUPERUSER=amol@mailinator.com
      - FIRST_SUPERUSER_PASSWORD=abcd1234
    ports:
      - '8080:8080'
    volumes:
      - '.:/src'
    command:
      [
        "uvicorn",
        'src.main:app',
        '--host',
        "0.0.0.0",
        '--port',
        '8080',
      ]
