---
name: 01 Basic Docker Build
# simplest workflow possible

on:
  push:
    branches:
      - main
      - ci-cd
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      # Multiple platform support
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      # Add caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # this will not push to docker / ensuring the docker image is available for next actions
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # security scanning
      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.run_id }}
          exit-code: 0
          format: table

      # Docker metadata
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: thiteamol/users
          flavor: |
            latest=false
          tags: |
            type=raw,value=0.0.1
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

          # Multiple platform support
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
