name: Docker Build
'on':
  push:
    branches:
      - main
      - ci-cd
  pull_request: null
jobs:
  build-test-image:
    name: Build Image for Testing
    runs-on: ubuntu-latest
    needs: [pre-commit]
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 'ghcr.io/thite-amol/users:${{ github.run_id }}'
          cache-from: type=gha
          cache-to: 'type=gha,mode=max'
          platforms: linux/amd64
  scan-image:
    name: Scan Image with Trivy
    needs:
      - build-test-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Pull image to scan
        run: 'docker pull ghcr.io/thite-amol/users:"$GITHUB_RUN_ID"'
      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/thite-amol/users:${{ github.run_id }}'
          format: table
          exit-code: 0
  build-final-image:
    name: Build Final Image
    needs:
      - scan-image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      pull-requests: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Docker Metadata for Final Image Build
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: 'thiteamol/users,ghcr.io/thite-amol/users'
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Docker Build and Push to GHCR and Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: '${{ steps.docker_meta.outputs.tags }}'
          labels: '${{ steps.docker_meta.outputs.labels }}'
          cache-from: type=gha
          cache-to: 'type=gha,mode=max'
          platforms: linux/amd64
